#!/bin/sh

date="$(LANG=C date -u)"
PDF=$(mktemp $TMPDIR/swift.XXXX)
TXT=$(mktemp $TMPDIR/swift.XXXX)
REG_URL="http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf"
curl -o "$PDF" "$REG_URL"
pdftotext "$PDF" "$TXT"
sha=$(shasum "$PDF" |cut -f1 -d' ')
release=$(grep -E ^Release "$TXT" | LANG=C tr '\200-\377' '-')

cat <<EOF
#!/usr/bin/python

"""
This file was autogenerated by the $0 script on $date.
"""

__copyright__ = 'Copyright (c) 2014 Emanuele Pucciarelli, C.O.R.P. s.n.c.'
__license__ = '3-clause BSD'
__registry_url__ = '$REG_URL'
__registry_sha1__ = '$sha'
__registry_release__ = '$release'

IBAN_STRUCTURES = (
EOF
for structure in $(pdftotext "$PDF" - | grep -o -E '[A-Z]{2}2!n(\d+!?[nac])+')
do
	echo "    '$structure',"
done
cat <<EOF
)
EOF

rm "$PDF" "$TXT"