language: python

matrix:
    include:
        - python: "2.6"
          env: TOXENV=py26
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.2"
          env: TOXENV=py32
        - python: 3".3"
          env: TOXENV=py33
        - python: "3.4"
          env: TOXENV=py34
        - python: "pypy"
          env: TOXENV=pypy
        - env: TOXENV=docs 

install:
    - pip install tox

script:
    - tox
